image: node:lts

stages:
  - prepare
#  - test
  - deploy

.prepare:
  stage: prepare
  cache:
    key: lettercms-api
    paths:
      - node_modules
  script:
    - yarn
    - yarn global add vercel

prepare-production:
  extends: .prepare
  script: echo hello
  only:
    - master

# test:
#   image: docker:latest
#   stage: test
#   services:
#     - docker:dind
#     - mongo
#   variables:
#     MONGO_URL: 'mongodb://mongo/testing'
#   before_script:
#     - docker build -t microservices
#     - docker run -d -p 3009:3009 microservices
#   only:
#     - production

staging:
  stage: deploy
  variables:
    TYPE: staging
    HEROKU_APP: lettercms-api-staging
    ACCEPT: "Accept: application/vnd.heroku+json; version=3"
    AUTH: "Authorization: Bearer ${HEROKU_API_KEY}"
    CONTENT_TYPE: "Content-Type: application/json"
    BUILD_JSON: '{ "source_blob": {"url": "https://s3.us-south.cloud-object-storage.appdomain.cloud/davidsdevel-storage-cos-standard-y2b/lettercms-api.tgz","version": "$CI_COMMIT_SHORT_SHA"}}'
  before_script:
    - yarn
    - 'echo web: node dev > Procfile'
    - tar zcv --exclude='.next/cache' --wildcards -f master.tgz davidsdevel-* index.js dev.js yarn.lock package.json Procfile
    - node uploadBuild
  script:
    - curl -n -X POST https://api.heroku.com/apps/${HEROKU_APP}/builds -d "${BUILD_JSON}" -H "${CONTENT_TYPE}" -H "${ACCEPT}" -H "${AUTH}"
  environment:
    name: staging
    url: https://${HEROKU_APP}.herokuapp.com
  only:
    - master

.deploy-vercel:
  stage: deploy
  variables:
    PREVIEW_URL: https://$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG.$VERCEL_SCOPE.vercel.app
    VERCEL_SCOPE: lettercms
  environment:
    name: vercel/${VERCEL_PATH/davidsdevel-/}
    url: $PREVIEW_URL
  before_script:
    - cd $VERCEL_PATH
    - vercel secrets add my-mongodb-uri $MONGO_URL
    - vercel secrets add sentry-dsn $SENTRY_DSN
    - vercel secrets add jwt-token $JWT_AUTH
  script:
    - DEPLOYMENT_URL=$(vercel --name $CI_PROJECT_NAME --confirm -t $VERCEL_TOKEN)
    - vercel alias set $DEPLOYMENT_URL $PREVIEW_URL -t $VERCEL_TOKEN
  only:
    - production

deploy-account:
  extends: .deploy-vercel
  variables:
    VERCEL_PATH: davidsdevel-accounts
deploy-blog:
  extends: .deploy-vercel
  variables:
    VERCEL_PATH: davidsdevel-blog
deploy-page:
  extends: .deploy-vercel
  variables:
    VERCEL_PATH: davidsdevel-pages
deploy-post:
  extends: .deploy-vercel
  variables:
    VERCEL_PATH: davidsdevel-posts
deploy-stat:
  extends: .deploy-vercel
  variables:
    VERCEL_PATH: davidsdevel-stats
deploy-user:
  extends: .deploy-vercel
  variables:
    VERCEL_PATH: davidsdevel-users

# TODO: Deploy to Vercel
#
# production:
#   extends: staging
#   needs:
#     - job: build-production
#       artifacts: true
#   variables:
#     HEROKU_APP: lettercms-api
#     TYPE: latest
#     SENTRY_VERSION: '{"version": "${VERSION/v/}"}'
#   environment:
#     name: production
#   after_script:
#     - 'curl https://sentry.io/api/hooks/release/builtin/5410236/e0ed8ecb580d6fd8ebee31f724156e2fe3fe5d4fb2ba69014b64c2832e9b948b/ -X POST -H "${CONTENT_TYPE}" -d "${SENTRY_VERSION}"'
#   only:
#     - production
