image: node:lts

stages:
  - prepare-test

prepare-test:
  image: docker:latest
  stage: prepare-test
  services:
    - docker:dind
  script:
    - docker build -t microservices:latest
    - docker tag microservices:latest $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/microservices:latest
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/microservices:latest
  only:
    - docker-deploy

